name: 'Setup node'
description: 'Setup node and install dependencies'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: cy-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
      shell: bash
