name: 'Setup & build'
description: 'Setup node, install dependencies & build'
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-node
    - uses: actions/cache@v3
      id: build-cache
      with:
        path: |
          packages/bueno/dist
          packages/headless/dist
          packages/auth/dist
          packages/atomic/dist
          packages/atomic/docs
          packages/atomic/loader
          packages/atomic/storybook-static
          packages/atomic/www
          packages/quantic/docs/out
          packages/atomic-react/dist
          packages/atomic-hosted-page/dist
          packages/atomic-angular/projects/atomic-angular/dist
          packages/samples/headless-react
          packages/quantic/force-app/main/default/staticresources/coveoheadless
          packages/quantic/force-app/main/default/staticresources/coveobueno
          !node_modules
          !**/node_modules
          !package-lock.json
        key: ${{ github.sha }}
    - if: steps.build-cache.outputs.cache-hit != 'true'
      run: npm run build
      shell: bash
