name: 'Setup & build'
description: 'Setup node, install dependencies & build'
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7.26.3
        run_install: false
    - uses: actions/cache@v3
      id: build-cache
      with:
        path: |
          packages/bueno/dist
          packages/headless/dist
          packages/auth/dist
          packages/atomic/dist
          packages/atomic/docs
          packages/atomic/loader
          packages/atomic/storybook-static
          packages/atomic/www
          packages/quantic/docs/out
          packages/atomic-react/dist
          packages/atomic-angular/projects/atomic-angular/dist
          packages/samples/headless-react
          packages/quantic/force-app/main/default/staticresources/coveoheadless
          packages/quantic/force-app/main/default/staticresources/coveobueno
          !node_modules
          !**/node_modules
        key: ${{ github.sha }}
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: cy-${{ hashFiles('**/pnpm-lock.yaml') }}
    - run: pnpm i
      shell: bash
    - if: steps.build-cache.outputs.cache-hit != 'true'
      run: pnpm build
      shell: bash
    - if: steps.build-cache.outputs.cache-hit != 'true'
      run: pnpm doc:generate
      shell: bash
