name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          npm i
          npx lerna bootstrap
          npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./packages/atomic
          start: npm run start:prod:background
