name: End-to-end tests Atomic
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup & Build
        run: |
          npm ci
          npx lerna bootstrap --ci
          npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./packages/atomic
          start: npm run start:prod
          wait-on: 'http://localhost:3333'
