name: 'package-lock.json root validator'

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/package-lock.json'
      - '**/pnpm-lock.yaml'
      - 'package-lock.json'
      - '!pnpm-lock.yaml'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/package-lock.json'
      - '**/pnpm-lock.yaml'
      - 'package-lock.json'
      - '!pnpm-lock.yaml'

jobs:
  lockfile-outside-of-root:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
