name: Snyk
on:
  push:
    branches:
      - master
  pull_request:
  workflow_run:
    workflows:
      - Master Robot
      - Manual package creation
    types:
      - completed
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      - name: Prepare snyk
        run: |
          npm ci
          yarn install --no-immutable --mode=skip-build
          npm run setup:snyk
      - name: Snyk Monitor
        continue-on-error: true
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk monitor --yarn-workspaces
      - name: Snyk Test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk test --yarn-workspaces --sarif-file-output=./sarifs/snyk.sarif
      - name: Snyk Code
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk code test --all-projects --sarif > ./sarifs/snyk-code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@04df1262e6247151b5ac09cd2c303ac36ad3f62b # v2
        with:
          sarif_file: ./sarifs
