name: Snyk
on:
  push:
    branches:
      - master
  pull_request:
  workflow_run:
    workflows:
      - Master Robot
      - Manual package creation
    types:
      - completed
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
        with:
          version: 7.26.3
          run_install: false
      - name: Prepare snyk
        run: |
          yarn install --no-immutable --mode=skip-build
          pnpm setup:snyk
      - name: Snyk Monitor
        continue-on-error: true
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: pnpm exec snyk monitor --yarn-workspaces
      - name: Snyk Test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: pnpm exec snyk test --yarn-workspaces --sarif-file-output=./sarifs/snyk.sarif
      - name: Snyk Code
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: pnpm exec snyk code test --all-projects --sarif > ./sarifs/snyk-code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@515828d97454b8354517688ddc5b48402b723750 # v2
        with:
          sarif_file: ./sarifs
